language: cpp
dist: xenial

services:
  - docker

env:
  global:
    - DOCKER_IMAGE="mellery451/rippled-ci-builder:2019-08-26"
    - VERBOSE_BUILD=true
    - MAX_TIME_MIN=80
    - CACHE_DIR=${TRAVIS_HOME}/_cache

before_install:
  - if [ "$(uname)" = "Darwin" ] ; then export NUM_PROCESSORS=$(sysctl -n hw.physicalcpu); else export NUM_PROCESSORS=$(nproc); fi
  - echo "NUM PROC is ${NUM_PROCESSORS}"
  - if [ "$(uname)" = "Linux" ] ; then docker pull ${DOCKER_IMAGE}; fi
  - if [ "${MATRIX_EVAL}" != "" ] ; then eval "${MATRIX_EVAL}"; fi
  - if [ "${CMAKE_ADD}" != "" ] ; then export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} ${CMAKE_ADD}"; fi

matrix:
  fast_finish: true
  include:
    # debug builds
    - compiler: gcc-8
      name: gcc-8, debug
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Debug
    - compiler: clang-8
      name: clang-8, debug
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - BUILD_TYPE=Debug
    # release builds
    - compiler: gcc-8
      name: gcc-8, release
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Release
    - compiler: clang-8
      name: clang-8, release
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - BUILD_TYPE=Release
    # coverage
    - compiler: gcc-8
      name: coverage
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - BUILD_TYPE=Debug
        - COVERAGE=true

script:
  - travis_wait ${MAX_TIME_MIN} ci/build-in-docker.sh

notifications:
  email: false



