sudo: false
language: cpp
dist: xenial

env:
  global:
    # Maintenance note: to move to a new version
    # of boost, update both BOOST_ROOT and BOOST_URL.
    # Note that for simplicity, BOOST_ROOT's final
    # namepart must match the folder name internal
    # to boost's .tar.gz.
    - LCOV_ROOT=$HOME/lcov
    - LCOV_EXCLUDE_FILES="*/src/test/*"
    - BOOST_ROOT=$HOME/boost_1_70_0
    - BOOST_URL='http://sourceforge.net/projects/boost/files/boost/1.70.0/boost_1_70_0.tar.gz'
    - VERBOSE_BUILD=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - gcc-7
      - g++-7
      - gcc-8
      - g++-8
      - python-software-properties
      - protobuf-compiler
      - libprotobuf-dev
      - libssl-dev
      - libstdc++6
      - binutils-gold
      - gdb
      - texinfo
      - cmake
      - lcov
      - llvm-8
      - clang-8

matrix:
  include:

    - compiler: clang-8
      env:
        - BUILD_TYPE=Debug
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

    - compiler: gcc-8
      env:
        - BUILD_TYPE=Release
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - compiler: clang-8
      env:
        - BUILD_TYPE=Release
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

    - compiler: gcc-8
      env:
        - BUILD_TYPE=Debug
        - CMAKE_EXTRA_ARGS=-Drippled_tag=master
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - compiler: gcc-8
      env:
        - BUILD_TYPE=Debug
        - CMAKE_EXTRA_ARGS=-Drippled_tag=develop
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

cache:
  directories:
    - $BOOST_ROOT

before_install:
  - if [ "${MATRIX_EVAL}" != "" ] ; then eval "${MATRIX_EVAL}"; fi
  - ( ci/install-dependencies.sh )
  - export PATH=/usr/local/bin:$PATH

script:
  - ci/build-and-test.sh

notifications:
  email:
    false

